import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Hoodie Sweatshirt',
    description: 'A cozy and stylish hoodie sweatshirt, perfect for keeping warm and comfortable.',
    price: 3500.00,
    originalPrice: 6000.00,
    onSale: true,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/01/Image-7@2x-300x300.png',
    hint: 'hoodie sweatshirt',
    category: 'Hoodies',
    rating: {
      rate: 4.6,
      count: 150,
    },
  },
  {
    id: '2',
    name: 'Long Sleeves Sweatshirt',
    description: 'A classic long-sleeved sweatshirt for a comfortable and casual look.',
    price: 3500.00,
    originalPrice: 6000.00,
    onSale: true,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/03/SHIRT-300x300.jpg',
    hint: 'long sleeve shirt',
    category: 'T-Shirts',
    rating: {
      rate: 4.5,
      count: 130,
    },
  },
  {
    id: '3',
    name: 'Men’s Premium T-Shirt',
    description: 'A premium quality t-shirt for men, offering superior comfort and a great fit.',
    price: 2500.00,
    originalPrice: 7000.00,
    onSale: true,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/01/sku-1@2x-300x300.png',
    hint: 'premium t-shirt',
    category: 'T-Shirts',
    rating: {
      rate: 4.8,
      count: 220,
    },
  },
  {
    id: '4',
    name: 'Phone Case',
    description: 'A durable and stylish phone case to protect your device.',
    price: 2000.00,
    originalPrice: 3000.00,
    onSale: true,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/03/Phone-case-600x600.jpg',
    hint: 'phone case',
    category: 'Accessories',
    rating: {
      rate: 4.7,
      count: 180,
    },
  },
  {
    id: '5',
    name: 'T-Shirt',
    description: 'A comfortable and versatile t-shirt for everyday wear.',
    price: 2000.00,
    onSale: false,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/01/Image-9@2x-1-300x300.png',
    hint: 'plain t-shirt',
    category: 'T-Shirts',
    rating: {
      rate: 4.4,
      count: 90,
    },
  },
  {
    id: '6',
    name: 'Tote Bag',
    description: 'A stylish and spacious tote bag, perfect for carrying your essentials.',
    price: 2000.00,
    originalPrice: 3000.00,
    onSale: true,
    image: 'https://smilesgiftings.com/wp-content/uploads/2024/03/Tote-bag-300x300.jpg',
    hint: 'tote bag',
    category: 'Accessories',
    rating: {
      rate: 4.9,
      count: 250,
    },
  },
];
